// Mocks generated by Mockito 5.4.4 from annotations
// in e_receitasus/test/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:e_receitasus/models/professional_type.dart' as _i5;
import 'package:e_receitasus/models/user_model.dart' as _i2;
import 'package:e_receitasus/services/auth_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i3.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> registerWithProfessionalInfo({
    required String? firstName,
    required String? lastName,
    required String? email,
    required DateTime? birthDate,
    required String? password,
    required _i5.ProfessionalType? professionalType,
    String? professionalId,
    String? professionalState,
    String? specialty,
    String? zipCode,
    String? street,
    String? streetNumber,
    String? complement,
    String? district,
    String? addressCity,
    String? addressState,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithProfessionalInfo,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #birthDate: birthDate,
            #password: password,
            #professionalType: professionalType,
            #professionalId: professionalId,
            #professionalState: professionalState,
            #specialty: specialty,
            #zipCode: zipCode,
            #street: street,
            #streetNumber: streetNumber,
            #complement: complement,
            #district: district,
            #addressCity: addressCity,
            #addressState: addressState,
          },
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #registerWithProfessionalInfo,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #birthDate: birthDate,
              #password: password,
              #professionalType: professionalType,
              #professionalId: professionalId,
              #professionalState: professionalState,
              #specialty: specialty,
              #zipCode: zipCode,
              #street: street,
              #streetNumber: streetNumber,
              #complement: complement,
              #district: district,
              #addressCity: addressCity,
              #addressState: addressState,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> registerPatient({
    required String? firstName,
    required String? lastName,
    required String? email,
    required DateTime? birthDate,
    required String? password,
    required String? phone,
    String? cns,
    String? cpf,
    String? socialName,
    String? motherParentName,
    String? birthCity,
    String? birthState,
    String? gender,
    String? ethnicity,
    String? maritalStatus,
    String? education,
    String? zipCode,
    String? street,
    String? streetNumber,
    String? complement,
    String? district,
    String? addressCity,
    String? addressState,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerPatient,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #birthDate: birthDate,
            #password: password,
            #phone: phone,
            #cns: cns,
            #cpf: cpf,
            #socialName: socialName,
            #motherParentName: motherParentName,
            #birthCity: birthCity,
            #birthState: birthState,
            #gender: gender,
            #ethnicity: ethnicity,
            #maritalStatus: maritalStatus,
            #education: education,
            #zipCode: zipCode,
            #street: street,
            #streetNumber: streetNumber,
            #complement: complement,
            #district: district,
            #addressCity: addressCity,
            #addressState: addressState,
          },
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #registerPatient,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #birthDate: birthDate,
              #password: password,
              #phone: phone,
              #cns: cns,
              #cpf: cpf,
              #socialName: socialName,
              #motherParentName: motherParentName,
              #birthCity: birthCity,
              #birthState: birthState,
              #gender: gender,
              #ethnicity: ethnicity,
              #maritalStatus: maritalStatus,
              #education: education,
              #zipCode: zipCode,
              #street: street,
              #streetNumber: streetNumber,
              #complement: complement,
              #district: district,
              #addressCity: addressCity,
              #addressState: addressState,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
