// Mocks generated by Mockito 5.4.4 from annotations
// in e_receitasus/test/renewal_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:e_receitasus/models/renewal_request_model.dart' as _i4;
import 'package:e_receitasus/models/user_model.dart' as _i5;
import 'package:e_receitasus/services/renewal_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IRenewalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRenewalService extends _i1.Mock implements _i2.IRenewalService {
  MockIRenewalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.RenewalRequestModel>> streamMyRenewals() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamMyRenewals,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.RenewalRequestModel>>.empty(),
      ) as _i3.Stream<List<_i4.RenewalRequestModel>>);

  @override
  _i3.Future<void> requestRenewal(
    String? prescriptionId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestRenewal,
          [prescriptionId],
          {#notes: notes},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.RenewalRequestModel>> streamPendingTriage() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamPendingTriage,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.RenewalRequestModel>>.empty(),
      ) as _i3.Stream<List<_i4.RenewalRequestModel>>);

  @override
  _i3.Future<void> approveTriage(
    String? id, {
    String? nurseNotes,
    required String? doctorUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveTriage,
          [id],
          {
            #nurseNotes: nurseNotes,
            #doctorUserId: doctorUserId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rejectTriage(
    String? id, {
    required String? nurseNotes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectTriage,
          [id],
          {#nurseNotes: nurseNotes},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.RenewalRequestModel>> streamTriagedForDoctor() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamTriagedForDoctor,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.RenewalRequestModel>>.empty(),
      ) as _i3.Stream<List<_i4.RenewalRequestModel>>);

  @override
  _i3.Future<void> markAsPrescribed(
    String? id,
    String? renewedPrescriptionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsPrescribed,
          [
            id,
            renewedPrescriptionId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.UserModel>> fetchDoctors() => (super.noSuchMethod(
        Invocation.method(
          #fetchDoctors,
          [],
        ),
        returnValue: _i3.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i3.Future<List<_i5.UserModel>>);
}
